version: "3.8"
services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    container_name: "mini_market_dev"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=mini_market_dev
    ports:
      - '5432:5432'
